# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c96b6c2571c6c8ab65c9976d5d699a5b361c0fdad5454bb9f56c2873fd8b3823bd79a5abe578f3560c42d68595d1ca779de20d96ff52f6dc35e829584148d06

test:
  secret_key_base: f972b1b27624549d0440abc5cac6c806359e65fe85c50cc571a9b6a2da93f83ab3b5c96abaa063ff4e2fa0d0c90197592d5bc03ba9fd9541c9d695db0c957b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
